import { Component, ChangeDetectionStrategy, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { GeminiService } from '../../services/gemini.service';
import { UserService } from '../../services/user.service';
import { DataService } from '../../services/data.service';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { marked } from 'marked';

declare const jspdf: any;

@Component({
  selector: 'app-ai-diet-coach',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="space-y-6">
      <header>
        <h1 class="text-3xl font-bold text-white">AI Diet + Workout Coach</h1>
        <p class="text-gray-400">Get a personalized wellness plan generated by your AI Coach.</p>
      </header>

      @if (!hasApiKey()) {
        <div class="bg-red-900/50 border border-red-500/50 rounded-lg p-4 text-center">
          <p class="text-red-300">AI features are disabled. Please configure the NEXT_PUBLIC_GEMINI_API_KEY in your Vercel project settings and redeploy.</p>
        </div>
      }

      <!-- User Stats -->
      <div class="bg-[#0b0b12] p-4 rounded-lg border border-white/10">
        <h3 class="text-lg font-semibold text-gray-200 mb-3">Your Current Stats</h3>
        <div class="grid grid-cols-2 md:grid-cols-4 gap-4 text-center">
          <div>
            <p class="text-sm text-gray-400">Current Weight</p>
            <p class="text-xl font-bold text-[#00E0B8]">{{ currentWeightKg() ? currentWeightKg() + ' kg' : 'N/A' }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-400">Height</p>
            <p class="text-xl font-bold text-white">{{ userHeightCm() ? userHeightCm() + ' cm' : 'N/A' }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-400">BMI</p>
            <p class="text-xl font-bold text-[#7C5CFF]">{{ bmi() ?? 'N/A' }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-400">Category</p>
            <p class="text-xl font-bold text-white">{{ bmiCategory() }}</p>
          </div>
        </div>
        @if (!currentWeightKg()) {
          <p class="text-xs text-center text-amber-500 mt-3">Log your weight in the 'Weight AI' section to see your stats.</p>
        }
      </div>


      <!-- Preferences Form -->
      <div class="bg-[#131321] p-6 rounded-lg border border-white/10">
        <form (ngSubmit)="generatePlan()">
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <!-- Column 1 -->
            <div class="space-y-4">
              <div>
                <label for="language" class="block text-sm font-medium text-gray-300 mb-1">Language</label>
                <select id="language" [(ngModel)]="language" name="language" class="w-full bg-[#0b0b12] border border-gray-600 rounded-md p-3 text-white focus:outline-none focus:ring-2 focus:ring-[#7C5CFF]">
                  <option value="English">English</option>
                  <option value="Hindi">Hindi</option>
                  <option value="Gujarati">Gujarati</option>
                </select>
              </div>
              <div>
                <label for="dietType" class="block text-sm font-medium text-gray-300 mb-1">Dietary Preference</label>
                <select id="dietType" [(ngModel)]="dietType" name="dietType" class="w-full bg-[#0b0b12] border border-gray-600 rounded-md p-3 text-white focus:outline-none focus:ring-2 focus:ring-[#7C5CFF]">
                  <option value="Vegetarian">Vegetarian</option>
                  <option value="Non-Vegetarian">Non-Vegetarian</option>
                  <option value="Vegan">Vegan</option>
                  <option value="Keto">Keto</option>
                  <option value="Indian Traditional">Indian Traditional</option>
                </select>
              </div>
            </div>
            <!-- Column 2 -->
            <div class="space-y-4">
               <div>
                <label for="goal" class="block text-sm font-medium text-gray-300 mb-1">Primary Goal</label>
                <select id="goal" [(ngModel)]="dietGoal" name="goal" class="w-full bg-[#0b0b12] border border-gray-600 rounded-md p-3 text-white focus:outline-none focus:ring-2 focus:ring-[#7C5CFF]">
                  <option value="weight loss">Weight Loss</option>
                  <option value="muscle gain">Muscle Gain</option>
                  <option value="maintenance">Maintenance</option>
                  <option value="general health">General Health</option>
                </select>
              </div>
               <div>
                <label for="targetWeight" class="block text-sm font-medium text-gray-300 mb-1">Target Weight (kg)</label>
                <input id="targetWeight" type="number" [(ngModel)]="targetWeight" name="targetWeight" class="w-full bg-[#0b0b12] border border-gray-600 rounded-md p-3 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#7C5CFF]" placeholder="e.g., 75">
              </div>
            </div>
             <!-- Column 3 -->
             <div class="space-y-4">
                <div>
                  <label for="planType" class="block text-sm font-medium text-gray-300 mb-1">Plan Type</label>
                  <select id="planType" [(ngModel)]="planType" name="planType" class="w-full bg-[#0b0b12] border border-gray-600 rounded-md p-3 text-white focus:outline-none focus:ring-2 focus:ring-[#7C5CFF]">
                    <option value="diet">Diet Only</option>
                    <option value="diet-workout">Diet + Workout</option>
                    <option value="diet-workout-supplements">Diet + Workout + Supplements</option>
                  </select>
                </div>
                 <div>
                  <label for="planDuration" class="block text-sm font-medium text-gray-300 mb-1">Plan Duration</label>
                  <select id="planDuration" [(ngModel)]="planDuration" name="planDuration" class="w-full bg-[#0b0b12] border border-gray-600 rounded-md p-3 text-white focus:outline-none focus:ring-2 focus:ring-[#7C5CFF]">
                    <option value="1 month">1 Month</option>
                    <option value="3 months">3 Months</option>
                    <option value="9 months">9 Months</option>
                  </select>
                </div>
              </div>
          </div>
          <div class="mt-6">
            <label for="preferences" class="block text-sm font-medium text-gray-300 mb-1">Likes, Dislikes, Allergies</label>
            <textarea id="preferences" [(ngModel)]="preferences" name="preferences" rows="4" class="w-full bg-[#0b0b12] border border-gray-600 rounded-md p-3 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#7C5CFF]" placeholder="e.g., allergic to peanuts, dislike mushrooms, love spicy food"></textarea>
          </div>
          <div class="mt-6">
            <button type="submit" [disabled]="isLoading() || !hasApiKey()" class="w-full bg-[#7C5CFF] text-white px-5 py-3 rounded-md font-semibold hover:bg-[#6a48ff] disabled:bg-gray-600 disabled:cursor-not-allowed transition-colors">
              @if (isLoading()) {
                <i class="fa-solid fa-spinner fa-spin mr-2"></i>
                <span>Generating Plan...</span>
              } @else {
                <span>Generate My Wellness Plan</span>
              }
            </button>
          </div>
        </form>
      </div>

      <!-- AI Response -->
      @if(isLoading() || dietPlan()) {
        <section class="bg-[#131321] p-6 rounded-lg border border-white/10">
          <div class="flex justify-between items-center mb-4">
            <h2 class="text-xl font-semibold">Your AI-Generated Wellness Plan</h2>
            @if(dietPlan() && !isLoading()) {
              <button (click)="downloadAsPdf()" [disabled]="isDownloadingPdf()" class="px-4 py-2 bg-green-600/80 text-white rounded-md hover:bg-green-600 flex items-center justify-center gap-2 disabled:bg-green-600/40">
                @if (isDownloadingPdf()) {
                  <i class="fas fa-spinner fa-spin"></i> <span>Preparing...</span>
                } @else {
                  <i class="fas fa-file-pdf"></i> Download PDF
                }
              </button>
            }
          </div>
          @if (error()) {
            <p class="text-red-400">{{ error() }}</p>
          } @else {
            <div class="prose prose-sm md:prose-base prose-invert max-w-none space-y-4" [innerHTML]="sanitizedDietPlan()"></div>
          }
        </section>
      }
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AiDietCoachComponent {
  geminiService = inject(GeminiService);
  userService = inject(UserService);
  dataService = inject(DataService);
  sanitizer = inject(DomSanitizer);

  // Form Signals
  language = signal<'English' | 'Hindi' | 'Gujarati'>('English');
  dietGoal = signal('weight loss');
  dietType = signal('Vegetarian');
  targetWeight = signal<number | null>(null);
  planType = signal<'diet' | 'diet-workout' | 'diet-workout-supplements'>('diet-workout');
  planDuration = signal<'1 month' | '3 months' | '9 months'>('1 month');
  preferences = signal('');
  
  // State Signals
  isLoading = signal(false);
  isDownloadingPdf = signal(false);
  error = signal<string | null>(null);
  dietPlan = signal<string | null>(null);
  sanitizedDietPlan = signal<SafeHtml>('');

  hasApiKey = computed(() => this.geminiService.hasApiKey());
  
  // Computed properties for stats
  latestWeight = computed(() => this.dataService.sortedWeightLogs().slice(-1)[0]);
  currentWeightKg = computed(() => this.latestWeight()?.weightKg ?? null);
  userHeightCm = computed(() => this.userService.currentUser()?.heightCm ?? null);
  userHeightM = computed(() => {
    const heightCm = this.userHeightCm();
    return heightCm ? heightCm / 100 : null;
  });

  bmi = computed(() => {
    const weight = this.currentWeightKg();
    const height = this.userHeightM();
    if (weight && height && height > 0) {
      return parseFloat((weight / (height * height)).toFixed(1));
    }
    return null;
  });

  bmiCategory = computed(() => {
    const bmiVal = this.bmi();
    if (!bmiVal) return 'N/A';
    if (bmiVal < 18.5) return 'Underweight';
    if (bmiVal < 25) return 'Normal weight';
    if (bmiVal < 30) return 'Overweight';
    return 'Obese';
  });


  generatePlan(): void {
    this.isLoading.set(true);
    this.error.set(null);
    this.dietPlan.set('');
    this.sanitizedDietPlan.set('');

    const user = this.userService.currentUser();

    const planComponents = {
        'diet': '- A detailed Indian-style diet plan.',
        'diet-workout': '- A detailed Indian-style diet plan.\n- A complementary workout schedule.',
        'diet-workout-supplements': '- A detailed Indian-style diet plan.\n- A complementary workout schedule.\n- Recommendations for natural, traditional Indian supplements.'
    };

    let prompt = `Act as a friendly, motivational wellness coach with a personality like Chetan Bhagat. My name is ${user?.name || 'friend'}. Address me directly by my name.
Create a personalized wellness plan for me in the ${this.language()} language.

My Details:
- Age: ${user?.age}
- Gender: ${user?.gender}
- Height: ${this.userHeightCm()} cm
- Current Weight: ${this.currentWeightKg() ? this.currentWeightKg() + ' kg' : 'Not specified'}
- Body Mass Index (BMI): ${this.bmi() ? this.bmi() + ' (' + this.bmiCategory() + ')' : 'Not calculated'}

My Goals:
- Primary Goal: ${this.dietGoal()}
- Target Weight: ${this.targetWeight() ? this.targetWeight() + ' kg' : 'Not specified'}
- Plan Duration: ${this.planDuration()}
- Dietary Preference: ${this.dietType()}
- Other Preferences/Allergies: ${this.preferences().trim() || 'None'}

Plan Components to Include:
${planComponents[this.planType()]}

Instructions:
- The tone should be encouraging, relatable, and use simple language.
- For longer plans (3 or 9 months), provide a detailed sample week and then outline the principles, food groups, and variety to maintain for the rest of the duration, rather than a rigid day-by-day plan.
- Structure the response with clear markdown headings for each section (e.g., "## Your Diet Plan", "### Breakfast", "## Your Workout Routine"). Use '##' for main sections and '###' for sub-sections. Use '*' or '-' for list items.
- IMPORTANT: Conclude with a friendly closing statement. The disclaimer should state: "This plan was created for you by your MOODY AI Coach. It's a great starting point, but always listen to your body and consult a healthcare professional for personalized advice." Do NOT use the words "AI-generated".

Now, create my personalized plan.
`;

    this.geminiService.generateDietPlanStream(prompt).subscribe({
      next: (chunk) => {
        this.dietPlan.update(current => (current ?? '') + chunk);
        try {
            const parsedHtml = marked.parse(this.dietPlan() ?? '');
            this.sanitizedDietPlan.set(this.sanitizer.bypassSecurityTrustHtml(parsedHtml as string));
        } catch(e) {
            console.error("Markdown parsing error", e);
            this.sanitizedDietPlan.set(this.dietPlan() ?? '');
        }
      },
      error: (err) => {
        console.error('Error generating diet plan:', err);
        this.error.set('Sorry, I had trouble generating a diet plan. Please try again.');
        this.isLoading.set(false);
      },
      complete: () => {
        this.isLoading.set(false);
      }
    });
  }
  
  private arrayBufferToBase64(buffer: ArrayBuffer): string {
    let binary = '';
    const bytes = new Uint8Array(buffer);
    const len = bytes.byteLength;
    for (let i = 0; i < len; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return window.btoa(binary);
  }

  async downloadAsPdf(): Promise<void> {
    const planText = this.dietPlan();
    if (!planText || this.isDownloadingPdf()) return;

    this.isDownloadingPdf.set(true);

    try {
        const { jsPDF } = jspdf;
        const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
        
        const selectedLanguage = this.language();

        if (selectedLanguage === 'Hindi' || selectedLanguage === 'Gujarati') {
            const fontName = selectedLanguage === 'Hindi' ? 'NotoSansDevanagari' : 'NotoSansGujarati';
            const fontUrl = selectedLanguage === 'Hindi' 
                ? 'https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/notosansdevanagari/NotoSansDevanagari-Regular.ttf'
                : 'https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/notosansgujarati/NotoSansGujarati-Regular.ttf';
            
            try {
                const fontBlob = await fetch(fontUrl).then(res => res.blob());
                const fontBuffer = await fontBlob.arrayBuffer();
                const fontBase64 = this.arrayBufferToBase64(fontBuffer);
                const fileName = `${fontName}.ttf`;

                doc.addFileToVFS(fileName, fontBase64);
                doc.addFont(fileName, fontName, 'normal');
                doc.setFont(fontName);
            } catch (fontError) {
                console.error("Failed to load custom font:", fontError);
                doc.setFont('helvetica');
                doc.text("Error: Could not load language font. Content may not display correctly.", 15, 20);
            }
        } else {
            doc.setFont('helvetica');
        }
        
        const margin = 15;
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const usableWidth = pageWidth - 2 * margin;
        let y = 20;

        const checkY = (increment: number) => {
            if (y + increment > pageHeight - margin) {
                doc.addPage();
                y = margin;
            }
        };

        doc.setFontSize(18);
        doc.setFont(undefined, 'bold');
        doc.text('Your AI Diet + Workout Coach Plan', pageWidth / 2, y, { align: 'center' });
        y += 15;

        const lines = planText.split('\n');

        for (const line of lines) {
            const trimmedLine = line.trim();
            const cleanedLine = trimmedLine.replace(/\*\*(.*?)\*\*/g, '$1').replace(/_(.*?)_/g, '$1');

            if (cleanedLine.startsWith('### ')) {
                checkY(12);
                y += 6;
                doc.setFont(undefined, 'bold');
                doc.setFontSize(12);
                const title = cleanedLine.substring(4).trim();
                const splitTitle = doc.splitTextToSize(title, usableWidth);
                doc.text(splitTitle, margin, y);
                y += (splitTitle.length * 6) + 2;
            } else if (cleanedLine.startsWith('## ')) {
                checkY(15);
                y += 8;
                doc.setFont(undefined, 'bold');
                doc.setFontSize(14);
                const title = cleanedLine.substring(3).trim();
                const splitTitle = doc.splitTextToSize(title, usableWidth);
                doc.text(splitTitle, margin, y);
                y += (splitTitle.length * 7) + 2;
            } else if (cleanedLine.startsWith('* ') || cleanedLine.startsWith('- ')) {
                checkY(10);
                doc.setFont(undefined, 'normal');
                doc.setFontSize(10);
                const item = '• ' + cleanedLine.substring(2).trim();
                const splitItem = doc.splitTextToSize(item, usableWidth - 5);
                doc.text(splitItem, margin + 5, y);
                y += splitItem.length * 5;
            } else if (cleanedLine.length > 0) {
                checkY(10);
                doc.setFont(undefined, 'normal');
                doc.setFontSize(10);
                const paragraph = doc.splitTextToSize(cleanedLine, usableWidth);
                doc.text(paragraph, margin, y);
                y += (paragraph.length * 5) + 4;
            } else {
                checkY(5);
                y += 4;
            }
        }
        
        doc.save(`MOODY_AI_Wellness_Plan.pdf`);
    } catch (e) {
        console.error("Error creating PDF:", e);
    } finally {
        this.isDownloadingPdf.set(false);
    }
  }
}
